MVC_mvc/mvc/Models/ErrorViewModel.cs
using System;

namespace mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
    
}

MVC_mvc/mvc/ViewModels/NewPostViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace mvc.ViewModels
{
    public class NewPostViewModel
    {
        [Required]
        [DisplayName("Sarlavxa")]
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string Tags { get; set; }
        
        [FromForm]
        public IFormFile HeaderImage { get; set; }
        
        
    }
}

MVC_mvc/mvc/ViewModels/ResultViewModel.cs
namespace mvc.ViewModels
{
    public class ResultViewModel
    {
        public string X1 { get; set; }
        public string X2 { get; set; }
        public bool HasRoots { get; set; }
        
        
    }
}

MVC_mvc/mvc/ViewModels/SquareRootViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace mvc.ViewModels
{
    public class SquareRootViewModel
    {
        [Required]
        public double A { get; set; }

        [Required]

        public double B { get; set; }

        [Required]

        public double C { get; set; }
        
        public string X1 { get; set; }
        public string X2 { get; set; }
        
        public bool HasRoots { get; set; } = false;
        
        
        
    }
}

MVC_mvc/mvc/Controllers/MathController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc.ViewModels;

namespace   mvc.Controllers
{
    [Route("[controller]")]
    public class MathController : Controller
    {
        private readonly ILogger<MathController> _logger;

        public MathController(ILogger<MathController> logger)
        {
            _logger = logger;
        }

        [HttpGet("sqrt")]
        public IActionResult SquareRoot()
        {
            return View();
        }

        [HttpPut("sqrt")]
        public IActionResult SquareRoot([FromForm]SquareRootViewModel model)
        {
            var disc = Math.Pow(model.B, 2) -4 * model.A * model.C;

            model.HasRoots = disc >= 0; 

            if(disc >= 0)
            {
                model.X1 =  model.X2 = $"{(-1) * model.B / (model.A * 2)}"; 
            }
            else if(disc > 0)
            {
                model.X1 = $"{(-1) * model.B + Math.Sqrt(disc) / (model.A * 2)}";
                model.X2 = $"{(-1) * model.B - Math.Sqrt(disc) / (model.A * 2)}";
            }

            return RedirectToAction("result");
        }

        [HttpGet("result")]
        public IActionResult Result()
        {
            return View();
        }
        
    }
}

MVC_mvc/mvc/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc.ViewModels;

namespace   mvc.Controllers
{
    [Route("[controller]")]
    public class PostController : Controller
    {
        private readonly ILogger<PostController> _logger;

        public PostController(ILogger<PostController> logger)
        {
            _logger = logger;
        }

        [HttpGet("write")]
        public IActionResult WritePost()
        {
            return View();
        }

        public IActionResult WritePost([FromForm]NewPostViewModel model)
        {
            return Ok(model);
        }
        
    }
}

MVC_mvc/mvc/Views/Math/Result.cshtml
@model ResultViewModel

MVC_mvc/mvc/Views/Math/SquareRoot.cshtml
@model SquareRootViewModel

<form asp-controller="Math" asp-action="SquareRoot" mathod="post">
    <div class="row"> 
    <div class="col-5 mx-auto">
        <input asp-for="A" style="max-width: 30px" placeholder="A"/> X&#178; + 
        <input asp-for="B" style="max-width: 30px" placeholder="B"> X 
        <input asp-for="C" style="max-width: 30px" placeholder="C"> = 0
        <h5 class="mt-3"><button class="btn btn-primary" type="submit">Solve</button></h5>
    </div>
    </div>
</form>


@if(Model != null)
{
    @if(Model.HasRoots)
    {
        if(string.IsNullOrWhiteSpace(Model.X1) && Model.X1 == Model.X2)
        {
            <p>X1, X2 = @Model.X1</p>
        }
        else
        {
            <p>X1 = @Model.X1</p>
            <p>X1 = @Model.X1</p>
        }
    }
    else
    {
        <p>Javobi yo'q!</p>
    }
}

MVC_mvc/mvc/Views/Post/WritePost.cshtml
@model NewPostViewModel;

<form asp-controller="Post" asp-action="WritePost" method="post">
    <div class="row mb-4"> 
        <label asp-for="Title"></label>
        <input asp-for="Title"/>
        <span asp-validation-for="Title" class="text-denger"></span>
    </div>
    <div class="row mb-3"> 
            <label asp-for="Description"></label>
            <input asp-for="Description"/>
            <span asp-validation-for="Description" class="text-denger"></span>
    </div>
    <div class="row mb-3"> 
            <label asp-for="Content"></label>
            <input asp-for="Content"/>

            <span asp-validation-for="Content" class="text-denger"></span>
    </div>
    <div class="row mb-3"> 
            <label asp-for="Tags"></label>
            <input asp-for="Tags"/> 
            <span asp-validation-for="Tags" class="text-denger"></span>
    </div>
    <div class="row mb-3"> 
            <label asp-for="HeaderImage"></label>
            <input asp-for="HeaderImage" type="file" accept=".png, .jpeg, .jpg, .gif"/>
            <span asp-validation-for="HeaderImage" class="text-denger"></span>

    </div>

    <button class="btn btn-primary" type="submit">Publish</button>
</form>
 

MVC_mvc/mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>